version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: book
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8000:8000"

  adminer:
    image: adminer
    ports:
      - "8080:8080"